# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="loadmychunks" #mandatory
version="${version}" #mandatory
displayName="LoadMyChunks" #mandatory
logoFile="lmc.png" #optional
authors="Drathonix" #optional
description='''
An advanced chunk loader that temporarily shuts off after it has overstayed its welcome. Chunks that take excess time to tick will not be loaded.
'''
[[dependencies.loadmychunks]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[38,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.loadmychunks]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.20.2)"
   ordering="NONE"
   side="BOTH"
